apiVersion: v1
kind: Service
metadata:
  namespace: bdf-exalab
  name: sb-app
  labels:
    app: sb-app
spec:
  selector:              
    app: sb-app
  type: NodePort
  ports:
  - name: http              
    port: 80
    targetPort: sb-app

---
apiVersion: v1
kind: Service
metadata:
  namespace: bdf-exalab
  name: sb-app2
  labels:
    app: sb-app2
spec:
  selector:              
    app: sb-app
  type: NodePort
  ports:
  - name: http2           
    port: 81
    targetPort: sb-app2

        
